// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: noble/dollar/portal/v1/genesis.proto

package portal

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the genesis state of the Noble Dollar Portal submodule.
type GenesisState struct {
	// owner is the account that controls the Noble Dollar Portal.
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	// paused contains the genesis paused state of the Noble Dollar Portal.
	Paused bool `protobuf:"varint,2,opt,name=paused,proto3" json:"paused,omitempty"`
	// peers contains the genesis peers of the Noble Dollar Portal.
	Peers map[uint16]Peer `protobuf:"bytes,3,rep,name=peers,proto3,castkey=uint16" json:"peers" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// supported_bridging_paths contains the genesis supported bridging paths of the Noble Dollar Portal.
	SupportedBridgingPaths []SupportedBridgingPath `protobuf:"bytes,4,rep,name=supported_bridging_paths,json=supportedBridgingPaths,proto3" json:"supported_bridging_paths"`
	// nonce contains the next available nonce used for transfers out of the Noble Dollar Portal.
	Nonce uint32 `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_aeebf6cda203b8c6, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *GenesisState) GetPaused() bool {
	if m != nil {
		return m.Paused
	}
	return false
}

func (m *GenesisState) GetPeers() map[uint16]Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

func (m *GenesisState) GetSupportedBridgingPaths() []SupportedBridgingPath {
	if m != nil {
		return m.SupportedBridgingPaths
	}
	return nil
}

func (m *GenesisState) GetNonce() uint32 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "noble.dollar.portal.v1.GenesisState")
	proto.RegisterMapType((map[uint16]Peer)(nil), "noble.dollar.portal.v1.GenesisState.PeersEntry")
}

func init() {
	proto.RegisterFile("noble/dollar/portal/v1/genesis.proto", fileDescriptor_aeebf6cda203b8c6)
}

var fileDescriptor_aeebf6cda203b8c6 = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x31, 0x6f, 0xda, 0x40,
	0x14, 0xc7, 0x7d, 0x18, 0xa3, 0xf6, 0x28, 0x55, 0x75, 0x42, 0xc8, 0x45, 0xad, 0xb1, 0xda, 0x0e,
	0x5e, 0x38, 0x0b, 0x2a, 0xb5, 0x51, 0xb6, 0x58, 0x8a, 0xb2, 0x22, 0xa3, 0x64, 0xc8, 0x82, 0x0c,
	0x3e, 0x19, 0x2b, 0xe6, 0xce, 0xba, 0x3b, 0x93, 0x38, 0x63, 0xc6, 0x4c, 0xf9, 0x30, 0xf9, 0x10,
	0x8c, 0x28, 0x53, 0xa6, 0x24, 0x82, 0x2f, 0x12, 0xd9, 0xe7, 0x28, 0x19, 0x60, 0xbb, 0xf7, 0xfc,
	0xff, 0xff, 0x7f, 0xcf, 0xef, 0xc1, 0x3f, 0x94, 0x4d, 0x13, 0xe2, 0x86, 0x2c, 0x49, 0x02, 0xee,
	0xa6, 0x8c, 0xcb, 0x20, 0x71, 0x97, 0x03, 0x37, 0x22, 0x94, 0x88, 0x58, 0xe0, 0x94, 0x33, 0xc9,
	0x50, 0xa7, 0x54, 0x61, 0xa5, 0xc2, 0x4a, 0x85, 0x97, 0x83, 0xee, 0xf7, 0x19, 0x13, 0x0b, 0x26,
	0x26, 0xa5, 0xca, 0x55, 0x85, 0xb2, 0x74, 0xdb, 0x11, 0x8b, 0x98, 0xea, 0x17, 0xaf, 0xaa, 0xfb,
	0x7b, 0x0f, 0xae, 0x8a, 0x2c, 0x45, 0xbf, 0x6e, 0x75, 0xf8, 0xe5, 0x44, 0xf1, 0xc7, 0x32, 0x90,
	0x04, 0x61, 0x68, 0xb0, 0x4b, 0x4a, 0xb8, 0x09, 0x6c, 0xe0, 0x7c, 0xf6, 0xcc, 0x87, 0xfb, 0x7e,
	0xbb, 0x82, 0x1d, 0x85, 0x21, 0x27, 0x42, 0x8c, 0x25, 0x8f, 0x69, 0xe4, 0x2b, 0x19, 0xea, 0xc0,
	0x46, 0x1a, 0x64, 0x82, 0x84, 0x66, 0xcd, 0x06, 0xce, 0x27, 0xbf, 0xaa, 0xd0, 0x29, 0x34, 0x52,
	0x42, 0xb8, 0x30, 0x75, 0x5b, 0x77, 0x9a, 0x43, 0x17, 0xef, 0xfe, 0x2d, 0xfc, 0x11, 0x8e, 0x47,
	0x85, 0xe3, 0x98, 0x4a, 0x9e, 0x7b, 0x5f, 0x57, 0x4f, 0x3d, 0xed, 0xe6, 0xb9, 0xd7, 0xc8, 0x62,
	0x2a, 0x07, 0xff, 0x7c, 0x95, 0x86, 0x16, 0xd0, 0x14, 0x59, 0x5a, 0xd8, 0x49, 0x38, 0x99, 0xf2,
	0x38, 0x8c, 0x62, 0x1a, 0x4d, 0xd2, 0x40, 0xce, 0x85, 0x59, 0x2f, 0x49, 0xfd, 0x7d, 0xa4, 0xf1,
	0x9b, 0xcf, 0xab, 0x6c, 0xa3, 0x40, 0xce, 0xbd, 0x7a, 0xc1, 0xf1, 0x3b, 0x62, 0xd7, 0x47, 0x81,
	0xda, 0xd0, 0xa0, 0x8c, 0xce, 0x88, 0x69, 0xd8, 0xc0, 0x69, 0xf9, 0xaa, 0xe8, 0x9e, 0x41, 0xf8,
	0x3e, 0x29, 0xfa, 0x06, 0xf5, 0x0b, 0x92, 0x97, 0xfb, 0x6a, 0xf9, 0xc5, 0x13, 0x0d, 0xa1, 0xb1,
	0x0c, 0x92, 0x8c, 0x94, 0x2b, 0x69, 0x0e, 0x7f, 0xec, 0x9b, 0xa8, 0x08, 0xf1, 0x95, 0xf4, 0xb0,
	0x76, 0x00, 0xbc, 0xff, 0xab, 0x8d, 0x05, 0xd6, 0x1b, 0x0b, 0xbc, 0x6c, 0x2c, 0x70, 0xb7, 0xb5,
	0xb4, 0xf5, 0xd6, 0xd2, 0x1e, 0xb7, 0x96, 0x76, 0xfe, 0xb3, 0xf2, 0xaa, 0xa0, 0xab, 0xfc, 0xda,
	0x95, 0x79, 0x4a, 0x44, 0x75, 0xcb, 0x69, 0xa3, 0x3c, 0xe6, 0xdf, 0xd7, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xbe, 0x2b, 0x1e, 0xf2, 0x62, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Nonce != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x28
	}
	if len(m.SupportedBridgingPaths) > 0 {
		for iNdEx := len(m.SupportedBridgingPaths) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SupportedBridgingPaths[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Peers) > 0 {
		for k := range m.Peers {
			v := m.Peers[k]
			baseI := i
			{
				size, err := (&v).MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
			i = encodeVarintGenesis(dAtA, i, uint64(k))
			i--
			dAtA[i] = 0x8
			i = encodeVarintGenesis(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Paused {
		i--
		if m.Paused {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Paused {
		n += 2
	}
	if len(m.Peers) > 0 {
		for k, v := range m.Peers {
			_ = k
			_ = v
			l = v.Size()
			mapEntrySize := 1 + sovGenesis(uint64(k)) + 1 + l + sovGenesis(uint64(l))
			n += mapEntrySize + 1 + sovGenesis(uint64(mapEntrySize))
		}
	}
	if len(m.SupportedBridgingPaths) > 0 {
		for _, e := range m.SupportedBridgingPaths {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.Nonce != 0 {
		n += 1 + sovGenesis(uint64(m.Nonce))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Paused", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Paused = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Peers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Peers == nil {
				m.Peers = make(map[uint16]Peer)
			}
			var mapkey uint32
			mapvalue := &Peer{}
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGenesis
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenesis
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= uint32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenesis
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthGenesis
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthGenesis
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &Peer{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipGenesis(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthGenesis
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Peers[uint16(mapkey)] = *mapvalue
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SupportedBridgingPaths", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SupportedBridgingPaths = append(m.SupportedBridgingPaths, SupportedBridgingPath{})
			if err := m.SupportedBridgingPaths[len(m.SupportedBridgingPaths)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
