[profile.default]
remappings = ["@hyperlane/=node_modules/@hyperlane-xyz/core/contracts/", "forge-std/=node_modules/forge-std/src/"]

[lint]
exclude_lints = ["pascal-case-struct", "mixed-case-function", "screaming-snake-case-const"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
