// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: noble/dollar/vaults/v1/genesis.proto

package vaults

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the genesis state of the Noble Dollar Vaults submodule.
type GenesisState struct {
	// total_flexible_principal contains all the users positions inside Vaults.
	Positions []PositionEntry `protobuf:"bytes,2,rep,name=positions,proto3" json:"positions"`
	// rewards maps the rewards amounts by the index.
	Rewards []Reward `protobuf:"bytes,3,rep,name=rewards,proto3" json:"rewards"`
	// total_flexible_principal contains the total principal amount contained in the flexible Vault.
	TotalFlexiblePrincipal cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=total_flexible_principal,json=totalFlexiblePrincipal,proto3,customtype=cosmossdk.io/math.Int" json:"total_flexible_principal"`
	// paused represents the current pausing state of the Vaults.
	Paused PausedType `protobuf:"varint,5,opt,name=paused,proto3,enum=noble.dollar.vaults.v1.PausedType" json:"paused,omitempty"`
	// stats contains the genesis statistics around the Noble Dollar Vaults.
	Stats Stats `protobuf:"bytes,6,opt,name=stats,proto3" json:"stats"`
	// season_one_ended indicates whether Vaults Season One has ended.
	SeasonOneEnded bool `protobuf:"varint,7,opt,name=season_one_ended,json=seasonOneEnded,proto3" json:"season_one_ended,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175d63afe7542ef, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetPositions() []PositionEntry {
	if m != nil {
		return m.Positions
	}
	return nil
}

func (m *GenesisState) GetRewards() []Reward {
	if m != nil {
		return m.Rewards
	}
	return nil
}

func (m *GenesisState) GetPaused() PausedType {
	if m != nil {
		return m.Paused
	}
	return NONE
}

func (m *GenesisState) GetStats() Stats {
	if m != nil {
		return m.Stats
	}
	return Stats{}
}

func (m *GenesisState) GetSeasonOneEnded() bool {
	if m != nil {
		return m.SeasonOneEnded
	}
	return false
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "noble.dollar.vaults.v1.GenesisState")
}

func init() {
	proto.RegisterFile("noble/dollar/vaults/v1/genesis.proto", fileDescriptor_6175d63afe7542ef)
}

var fileDescriptor_6175d63afe7542ef = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x31, 0x6f, 0xd4, 0x30,
	0x14, 0xc7, 0x63, 0xae, 0xbd, 0x52, 0x17, 0x55, 0x10, 0x41, 0x15, 0x2a, 0x91, 0x46, 0x05, 0xa4,
	0x08, 0x09, 0x9b, 0x86, 0x89, 0x0e, 0x0c, 0x27, 0x15, 0x74, 0x13, 0x55, 0x60, 0x62, 0x89, 0x7c,
	0x8d, 0x39, 0x0c, 0x3e, 0x3b, 0xca, 0x73, 0x43, 0xc3, 0xa7, 0xe0, 0x53, 0x20, 0x46, 0x06, 0x3e,
	0x44, 0xc7, 0x13, 0x13, 0x62, 0x38, 0xa1, 0xbb, 0x81, 0xaf, 0x81, 0x62, 0xfb, 0xc4, 0xd2, 0x2c,
	0x51, 0xfc, 0xf7, 0xef, 0xff, 0x7f, 0xcf, 0xef, 0xe1, 0x07, 0x4a, 0x4f, 0x24, 0xa7, 0xa5, 0x96,
	0x92, 0xd5, 0xb4, 0x61, 0xe7, 0xd2, 0x00, 0x6d, 0x8e, 0xe8, 0x94, 0x2b, 0x0e, 0x02, 0x48, 0x55,
	0x6b, 0xa3, 0xc3, 0x3d, 0x4b, 0x11, 0x47, 0x11, 0x47, 0x91, 0xe6, 0x68, 0xff, 0x16, 0x9b, 0x09,
	0xa5, 0xa9, 0xfd, 0x3a, 0x74, 0xff, 0xee, 0x99, 0x86, 0x99, 0x86, 0xc2, 0x9e, 0xa8, 0x3b, 0xf8,
	0xab, 0xdb, 0x53, 0x3d, 0xd5, 0x4e, 0xef, 0xfe, 0xbc, 0x7a, 0xbf, 0xa7, 0x03, 0x5f, 0xc5, 0x42,
	0x87, 0x5f, 0x07, 0xf8, 0xc6, 0x4b, 0xd7, 0xd2, 0x6b, 0xc3, 0x0c, 0x0f, 0xc7, 0x78, 0xbb, 0xd2,
	0x20, 0x8c, 0xd0, 0x0a, 0xa2, 0x6b, 0xc9, 0x20, 0xdd, 0xc9, 0x1e, 0x92, 0xab, 0xbb, 0x24, 0xa7,
	0x1e, 0x3c, 0x51, 0xa6, 0x6e, 0x47, 0x1b, 0x97, 0x8b, 0x83, 0x20, 0xff, 0xef, 0x0e, 0x9f, 0xe3,
	0xad, 0x9a, 0x7f, 0x62, 0x75, 0x09, 0xd1, 0xc0, 0x06, 0xc5, 0x7d, 0x41, 0xb9, 0xc5, 0x7c, 0xc2,
	0xda, 0x14, 0x7e, 0xc0, 0x91, 0xd1, 0x86, 0xc9, 0xe2, 0x9d, 0xe4, 0x17, 0x62, 0x22, 0x79, 0x51,
	0xd5, 0x42, 0x9d, 0x89, 0x8a, 0xc9, 0x68, 0x23, 0x41, 0xe9, 0xf6, 0xe8, 0x49, 0x67, 0xf8, 0xbd,
	0x38, 0xb8, 0xe3, 0xc6, 0x01, 0xe5, 0x47, 0x22, 0x34, 0x9d, 0x31, 0xf3, 0x9e, 0x8c, 0x95, 0xf9,
	0xf9, 0xe3, 0x31, 0xf6, 0x73, 0x1a, 0x2b, 0xf3, 0xed, 0xef, 0xf7, 0x47, 0x28, 0xdf, 0xb3, 0x89,
	0x2f, 0x7c, 0xe0, 0xe9, 0x3a, 0x2f, 0x3c, 0xc6, 0xc3, 0x8a, 0x9d, 0x03, 0x2f, 0xa3, 0xcd, 0x04,
	0xa5, 0xbb, 0xd9, 0x61, 0xef, 0x9b, 0x2d, 0xf5, 0xa6, 0xad, 0x78, 0xee, 0x1d, 0xe1, 0x33, 0xbc,
	0x09, 0x86, 0x19, 0x88, 0x86, 0x09, 0x4a, 0x77, 0xb2, 0x7b, 0x7d, 0xd6, 0x6e, 0xc0, 0xe0, 0x1f,
	0xe9, 0x1c, 0x61, 0x8a, 0x6f, 0x02, 0x67, 0xa0, 0x55, 0xa1, 0x15, 0x2f, 0xb8, 0x2a, 0x79, 0x19,
	0x6d, 0x25, 0x28, 0xbd, 0x9e, 0xef, 0x3a, 0xfd, 0x95, 0xe2, 0x27, 0x9d, 0x3a, 0x3a, 0xbe, 0x5c,
	0xc6, 0x68, 0xbe, 0x8c, 0xd1, 0x9f, 0x65, 0x8c, 0xbe, 0xac, 0xe2, 0x60, 0xbe, 0x8a, 0x83, 0x5f,
	0xab, 0x38, 0x78, 0x9b, 0xf8, 0x42, 0xae, 0xea, 0x45, 0xfb, 0x99, 0x36, 0x19, 0x35, 0x6d, 0xc5,
	0xc1, 0xaf, 0x7a, 0x32, 0xb4, 0xbb, 0x7e, 0xfa, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xa2, 0xe0, 0xc8,
	0xf5, 0x94, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SeasonOneEnded {
		i--
		if m.SeasonOneEnded {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	{
		size, err := m.Stats.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if m.Paused != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Paused))
		i--
		dAtA[i] = 0x28
	}
	{
		size := m.TotalFlexiblePrincipal.Size()
		i -= size
		if _, err := m.TotalFlexiblePrincipal.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Rewards) > 0 {
		for iNdEx := len(m.Rewards) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Rewards[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Positions) > 0 {
		for iNdEx := len(m.Positions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Positions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Positions) > 0 {
		for _, e := range m.Positions {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Rewards) > 0 {
		for _, e := range m.Rewards {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.TotalFlexiblePrincipal.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.Paused != 0 {
		n += 1 + sovGenesis(uint64(m.Paused))
	}
	l = m.Stats.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.SeasonOneEnded {
		n += 2
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Positions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Positions = append(m.Positions, PositionEntry{})
			if err := m.Positions[len(m.Positions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rewards", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Rewards = append(m.Rewards, Reward{})
			if err := m.Rewards[len(m.Rewards)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalFlexiblePrincipal", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalFlexiblePrincipal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Paused", wireType)
			}
			m.Paused = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Paused |= PausedType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stats", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Stats.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SeasonOneEnded", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SeasonOneEnded = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
