// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: noble/dollar/vaults/v1/vaults.proto

package vaults

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// buf:lint:ignore ENUM_VALUE_PREFIX
type VaultType int32

const (
	// buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
	UNSPECIFIED VaultType = 0
	STAKED      VaultType = 1
	FLEXIBLE    VaultType = 2
)

var VaultType_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "STAKED",
	2: "FLEXIBLE",
}

var VaultType_value = map[string]int32{
	"UNSPECIFIED": 0,
	"STAKED":      1,
	"FLEXIBLE":    2,
}

func (x VaultType) String() string {
	return proto.EnumName(VaultType_name, int32(x))
}

func (VaultType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1a185cec7ba75cfc, []int{0}
}

// buf:lint:ignore ENUM_VALUE_PREFIX
type PausedType int32

const (
	// buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
	NONE   PausedType = 0
	LOCK   PausedType = 1
	UNLOCK PausedType = 2
	ALL    PausedType = 3
)

var PausedType_name = map[int32]string{
	0: "NONE",
	1: "LOCK",
	2: "UNLOCK",
	3: "ALL",
}

var PausedType_value = map[string]int32{
	"NONE":   0,
	"LOCK":   1,
	"UNLOCK": 2,
	"ALL":    3,
}

func (x PausedType) String() string {
	return proto.EnumName(PausedType_name, int32(x))
}

func (PausedType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1a185cec7ba75cfc, []int{1}
}

type Reward struct {
	Index   int64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Total   cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=total,proto3,customtype=cosmossdk.io/math.Int" json:"total"`
	Rewards cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=rewards,proto3,customtype=cosmossdk.io/math.Int" json:"rewards"`
}

func (m *Reward) Reset()         { *m = Reward{} }
func (m *Reward) String() string { return proto.CompactTextString(m) }
func (*Reward) ProtoMessage()    {}
func (*Reward) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a185cec7ba75cfc, []int{0}
}
func (m *Reward) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Reward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Reward.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Reward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reward.Merge(m, src)
}
func (m *Reward) XXX_Size() int {
	return m.Size()
}
func (m *Reward) XXX_DiscardUnknown() {
	xxx_messageInfo_Reward.DiscardUnknown(m)
}

var xxx_messageInfo_Reward proto.InternalMessageInfo

func (m *Reward) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type Position struct {
	Principal cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=principal,proto3,customtype=cosmossdk.io/math.Int" json:"principal"`
	Index     int64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Amount    cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
	Time      time.Time             `protobuf:"bytes,4,opt,name=time,proto3,stdtime" json:"time"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a185cec7ba75cfc, []int{1}
}
func (m *Position) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Position.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return m.Size()
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Position) GetTime() time.Time {
	if m != nil {
		return m.Time
	}
	return time.Time{}
}

type PositionEntry struct {
	Address   []byte                `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Vault     VaultType             `protobuf:"varint,2,opt,name=vault,proto3,enum=noble.dollar.vaults.v1.VaultType" json:"vault,omitempty"`
	Principal cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=principal,proto3,customtype=cosmossdk.io/math.Int" json:"principal"`
	Index     int64                 `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	Amount    cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
	Time      time.Time             `protobuf:"bytes,6,opt,name=time,proto3,stdtime" json:"time"`
}

func (m *PositionEntry) Reset()         { *m = PositionEntry{} }
func (m *PositionEntry) String() string { return proto.CompactTextString(m) }
func (*PositionEntry) ProtoMessage()    {}
func (*PositionEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a185cec7ba75cfc, []int{2}
}
func (m *PositionEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PositionEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PositionEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PositionEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PositionEntry.Merge(m, src)
}
func (m *PositionEntry) XXX_Size() int {
	return m.Size()
}
func (m *PositionEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_PositionEntry.DiscardUnknown(m)
}

var xxx_messageInfo_PositionEntry proto.InternalMessageInfo

func (m *PositionEntry) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *PositionEntry) GetVault() VaultType {
	if m != nil {
		return m.Vault
	}
	return UNSPECIFIED
}

func (m *PositionEntry) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *PositionEntry) GetTime() time.Time {
	if m != nil {
		return m.Time
	}
	return time.Time{}
}

type Stats struct {
	FlexibleTotalPrincipal                   cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=flexible_total_principal,json=flexibleTotalPrincipal,proto3,customtype=cosmossdk.io/math.Int" json:"flexible_total_principal"`
	FlexibleTotalUsers                       uint64                `protobuf:"varint,2,opt,name=flexible_total_users,json=flexibleTotalUsers,proto3" json:"flexible_total_users,omitempty"`
	FlexibleTotalDistributedRewardsPrincipal cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=flexible_total_distributed_rewards_principal,json=flexibleTotalDistributedRewardsPrincipal,proto3,customtype=cosmossdk.io/math.Int" json:"flexible_total_distributed_rewards_principal"`
	StakedTotalPrincipal                     cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=staked_total_principal,json=stakedTotalPrincipal,proto3,customtype=cosmossdk.io/math.Int" json:"staked_total_principal"`
	StakedTotalUsers                         uint64                `protobuf:"varint,5,opt,name=staked_total_users,json=stakedTotalUsers,proto3" json:"staked_total_users,omitempty"`
}

func (m *Stats) Reset()         { *m = Stats{} }
func (m *Stats) String() string { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()    {}
func (*Stats) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a185cec7ba75cfc, []int{3}
}
func (m *Stats) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Stats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Stats.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Stats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stats.Merge(m, src)
}
func (m *Stats) XXX_Size() int {
	return m.Size()
}
func (m *Stats) XXX_DiscardUnknown() {
	xxx_messageInfo_Stats.DiscardUnknown(m)
}

var xxx_messageInfo_Stats proto.InternalMessageInfo

func (m *Stats) GetFlexibleTotalUsers() uint64 {
	if m != nil {
		return m.FlexibleTotalUsers
	}
	return 0
}

func (m *Stats) GetStakedTotalUsers() uint64 {
	if m != nil {
		return m.StakedTotalUsers
	}
	return 0
}

func init() {
	proto.RegisterEnum("noble.dollar.vaults.v1.VaultType", VaultType_name, VaultType_value)
	proto.RegisterEnum("noble.dollar.vaults.v1.PausedType", PausedType_name, PausedType_value)
	proto.RegisterType((*Reward)(nil), "noble.dollar.vaults.v1.Reward")
	proto.RegisterType((*Position)(nil), "noble.dollar.vaults.v1.Position")
	proto.RegisterType((*PositionEntry)(nil), "noble.dollar.vaults.v1.PositionEntry")
	proto.RegisterType((*Stats)(nil), "noble.dollar.vaults.v1.Stats")
}

func init() {
	proto.RegisterFile("noble/dollar/vaults/v1/vaults.proto", fileDescriptor_1a185cec7ba75cfc)
}

var fileDescriptor_1a185cec7ba75cfc = []byte{
	// 662 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x41, 0x4f, 0x13, 0x41,
	0x14, 0xee, 0xb4, 0xdb, 0x52, 0x1e, 0xa8, 0xeb, 0xa4, 0x92, 0xda, 0xc3, 0xb6, 0xe2, 0xa5, 0x21,
	0xb8, 0x0b, 0x78, 0xd0, 0xa8, 0x17, 0x0a, 0x4b, 0xac, 0x34, 0xa5, 0x59, 0x8a, 0x31, 0x5e, 0x9a,
	0x2d, 0x3b, 0xd4, 0x95, 0xed, 0x4e, 0xb3, 0x33, 0xad, 0xd4, 0x5f, 0xe0, 0x91, 0xff, 0xe0, 0xc5,
	0xa3, 0x31, 0xfe, 0x08, 0x0e, 0xc6, 0x10, 0x4f, 0xc6, 0x03, 0x1a, 0x38, 0xf8, 0x07, 0xfc, 0x01,
	0x66, 0x67, 0xb6, 0x94, 0x22, 0x17, 0x0b, 0x97, 0xe6, 0xbd, 0x99, 0xf7, 0x7d, 0xdf, 0xcc, 0xf7,
	0xde, 0x74, 0xe1, 0xae, 0x4f, 0x9b, 0x1e, 0x31, 0x1c, 0xea, 0x79, 0x76, 0x60, 0xf4, 0xec, 0xae,
	0xc7, 0x99, 0xd1, 0x5b, 0x8c, 0x22, 0xbd, 0x13, 0x50, 0x4e, 0xf1, 0x8c, 0x28, 0xd2, 0x65, 0x91,
	0x1e, 0x6d, 0xf5, 0x16, 0x73, 0x37, 0xed, 0xb6, 0xeb, 0x53, 0x43, 0xfc, 0xca, 0xd2, 0xdc, 0xed,
	0x6d, 0xca, 0xda, 0x94, 0x35, 0x44, 0x66, 0xc8, 0x24, 0xda, 0xca, 0xb4, 0x68, 0x8b, 0xca, 0xf5,
	0x30, 0x8a, 0x56, 0xf3, 0x2d, 0x4a, 0x5b, 0x1e, 0x31, 0x44, 0xd6, 0xec, 0xee, 0x18, 0xdc, 0x6d,
	0x13, 0xc6, 0xed, 0x76, 0x47, 0x16, 0xcc, 0x7e, 0x42, 0x90, 0xb2, 0xc8, 0x1b, 0x3b, 0x70, 0x70,
	0x06, 0x92, 0xae, 0xef, 0x90, 0xbd, 0x2c, 0x2a, 0xa0, 0x62, 0xc2, 0x92, 0x09, 0x5e, 0x83, 0x24,
	0xa7, 0xdc, 0xf6, 0xb2, 0xf1, 0x02, 0x2a, 0x4e, 0x96, 0x16, 0x0e, 0x8e, 0xf2, 0xb1, 0x1f, 0x47,
	0xf9, 0x5b, 0x52, 0x9c, 0x39, 0xbb, 0xba, 0x4b, 0x8d, 0xb6, 0xcd, 0x5f, 0xe9, 0x65, 0x9f, 0x7f,
	0xfb, 0x7c, 0x0f, 0xa2, 0x53, 0x95, 0x7d, 0xfe, 0xe1, 0xf7, 0xc7, 0x39, 0x64, 0x49, 0x38, 0x7e,
	0x06, 0x13, 0x81, 0xd0, 0x61, 0xd9, 0xc4, 0x98, 0x4c, 0x03, 0x82, 0xd9, 0x3f, 0x08, 0xd2, 0x35,
	0xca, 0x5c, 0xee, 0x52, 0x1f, 0x57, 0x61, 0xb2, 0x13, 0xb8, 0xfe, 0xb6, 0xdb, 0xb1, 0x3d, 0x71,
	0xf4, 0x71, 0xa8, 0x87, 0x14, 0x43, 0x1b, 0xe2, 0x67, 0x6d, 0x78, 0x0a, 0x29, 0xbb, 0x4d, 0xbb,
	0x3e, 0x1f, 0xfb, 0xf4, 0x11, 0x1e, 0x3f, 0x04, 0x25, 0x6c, 0x42, 0x56, 0x29, 0xa0, 0xe2, 0xd4,
	0x52, 0x4e, 0x97, 0x1d, 0xd2, 0x07, 0x1d, 0xd2, 0xeb, 0x83, 0x0e, 0x95, 0xd2, 0xa1, 0xc6, 0xfe,
	0xcf, 0x3c, 0xb2, 0x04, 0x62, 0xf6, 0x4b, 0x1c, 0xae, 0x0d, 0xae, 0x6d, 0xfa, 0x3c, 0xe8, 0xe3,
	0x2c, 0x4c, 0xd8, 0x8e, 0x13, 0x10, 0xc6, 0xc4, 0xcd, 0xa7, 0xad, 0x41, 0x8a, 0x1f, 0x40, 0x52,
	0x4c, 0x92, 0xb8, 0xc5, 0xf5, 0xa5, 0x3b, 0xfa, 0xc5, 0x43, 0xa6, 0x3f, 0x0f, 0xa3, 0x7a, 0xbf,
	0x43, 0x2c, 0x59, 0x3f, 0x6a, 0x67, 0xe2, 0x0a, 0xed, 0x54, 0x2e, 0xb6, 0x33, 0x79, 0x45, 0x76,
	0xa6, 0xfe, 0xdb, 0xce, 0xaf, 0x09, 0x48, 0x6e, 0x72, 0x9b, 0x33, 0xfc, 0x1a, 0xb2, 0x3b, 0x1e,
	0xd9, 0x73, 0x9b, 0x1e, 0x69, 0x88, 0x69, 0x6d, 0x5c, 0x7e, 0xa2, 0x66, 0x06, 0x8c, 0xf5, 0x90,
	0xb0, 0x76, 0xea, 0xc7, 0x02, 0x64, 0xce, 0x69, 0x75, 0x19, 0x09, 0x98, 0xe8, 0x93, 0x62, 0xe1,
	0x11, 0xd4, 0x56, 0xb8, 0x83, 0xf7, 0x11, 0xcc, 0x9f, 0x83, 0x38, 0x2e, 0xe3, 0x81, 0xdb, 0xec,
	0x72, 0xe2, 0x34, 0xa2, 0x47, 0xd1, 0xb8, 0x7c, 0xd7, 0x8a, 0x23, 0xe2, 0xab, 0x43, 0x0d, 0xf9,
	0x07, 0xc1, 0x86, 0x97, 0xd8, 0x81, 0x19, 0xc6, 0xed, 0x5d, 0xe2, 0xfc, 0x63, 0x97, 0x32, 0xa6,
	0x76, 0x46, 0xf2, 0x9d, 0x33, 0x6b, 0x1e, 0xf0, 0x88, 0x8e, 0xb4, 0x2a, 0x29, 0xac, 0x52, 0xcf,
	0x20, 0x84, 0x51, 0x73, 0x4f, 0x60, 0xf2, 0x74, 0x9c, 0xf1, 0x0d, 0x98, 0xda, 0xaa, 0x6e, 0xd6,
	0xcc, 0x95, 0xf2, 0x5a, 0xd9, 0x5c, 0x55, 0x63, 0x18, 0x20, 0xb5, 0x59, 0x5f, 0x5e, 0x37, 0x57,
	0x55, 0x84, 0xa7, 0x21, 0xbd, 0x56, 0x31, 0x5f, 0x94, 0x4b, 0x15, 0x53, 0x8d, 0xe7, 0x94, 0x77,
	0xef, 0xb5, 0xd8, 0xdc, 0x63, 0x80, 0x9a, 0xdd, 0x65, 0xc4, 0x11, 0xf0, 0x34, 0x28, 0xd5, 0x8d,
	0xaa, 0xa9, 0xc6, 0xc2, 0xa8, 0xb2, 0xb1, 0xb2, 0xae, 0xa2, 0x90, 0x61, 0xab, 0x2a, 0xe2, 0x38,
	0x9e, 0x80, 0xc4, 0x72, 0xa5, 0xa2, 0x26, 0x24, 0xb8, 0xf4, 0xe8, 0xe0, 0x58, 0x43, 0x87, 0xc7,
	0x1a, 0xfa, 0x75, 0xac, 0xa1, 0xfd, 0x13, 0x2d, 0x76, 0x78, 0xa2, 0xc5, 0xbe, 0x9f, 0x68, 0xb1,
	0x97, 0x85, 0xe8, 0xc9, 0xc9, 0xf7, 0xb7, 0xd7, 0x7f, 0x6b, 0xf4, 0x96, 0x0c, 0xde, 0xef, 0x10,
	0x16, 0x7d, 0x05, 0x9a, 0x29, 0x31, 0xab, 0xf7, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x89, 0x72,
	0x05, 0x20, 0x2d, 0x06, 0x00, 0x00,
}

func (m *Reward) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Reward) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Reward) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Rewards.Size()
		i -= size
		if _, err := m.Rewards.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintVaults(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.Total.Size()
		i -= size
		if _, err := m.Total.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintVaults(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.Index != 0 {
		i = encodeVarintVaults(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Position) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Position) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Position) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.Time, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Time):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintVaults(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x22
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintVaults(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.Index != 0 {
		i = encodeVarintVaults(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x10
	}
	{
		size := m.Principal.Size()
		i -= size
		if _, err := m.Principal.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintVaults(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PositionEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PositionEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PositionEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.Time, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Time):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintVaults(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x32
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintVaults(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.Index != 0 {
		i = encodeVarintVaults(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x20
	}
	{
		size := m.Principal.Size()
		i -= size
		if _, err := m.Principal.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintVaults(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.Vault != 0 {
		i = encodeVarintVaults(dAtA, i, uint64(m.Vault))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintVaults(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Stats) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Stats) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Stats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.StakedTotalUsers != 0 {
		i = encodeVarintVaults(dAtA, i, uint64(m.StakedTotalUsers))
		i--
		dAtA[i] = 0x28
	}
	{
		size := m.StakedTotalPrincipal.Size()
		i -= size
		if _, err := m.StakedTotalPrincipal.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintVaults(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.FlexibleTotalDistributedRewardsPrincipal.Size()
		i -= size
		if _, err := m.FlexibleTotalDistributedRewardsPrincipal.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintVaults(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.FlexibleTotalUsers != 0 {
		i = encodeVarintVaults(dAtA, i, uint64(m.FlexibleTotalUsers))
		i--
		dAtA[i] = 0x10
	}
	{
		size := m.FlexibleTotalPrincipal.Size()
		i -= size
		if _, err := m.FlexibleTotalPrincipal.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintVaults(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintVaults(dAtA []byte, offset int, v uint64) int {
	offset -= sovVaults(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Reward) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Index != 0 {
		n += 1 + sovVaults(uint64(m.Index))
	}
	l = m.Total.Size()
	n += 1 + l + sovVaults(uint64(l))
	l = m.Rewards.Size()
	n += 1 + l + sovVaults(uint64(l))
	return n
}

func (m *Position) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Principal.Size()
	n += 1 + l + sovVaults(uint64(l))
	if m.Index != 0 {
		n += 1 + sovVaults(uint64(m.Index))
	}
	l = m.Amount.Size()
	n += 1 + l + sovVaults(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Time)
	n += 1 + l + sovVaults(uint64(l))
	return n
}

func (m *PositionEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovVaults(uint64(l))
	}
	if m.Vault != 0 {
		n += 1 + sovVaults(uint64(m.Vault))
	}
	l = m.Principal.Size()
	n += 1 + l + sovVaults(uint64(l))
	if m.Index != 0 {
		n += 1 + sovVaults(uint64(m.Index))
	}
	l = m.Amount.Size()
	n += 1 + l + sovVaults(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Time)
	n += 1 + l + sovVaults(uint64(l))
	return n
}

func (m *Stats) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.FlexibleTotalPrincipal.Size()
	n += 1 + l + sovVaults(uint64(l))
	if m.FlexibleTotalUsers != 0 {
		n += 1 + sovVaults(uint64(m.FlexibleTotalUsers))
	}
	l = m.FlexibleTotalDistributedRewardsPrincipal.Size()
	n += 1 + l + sovVaults(uint64(l))
	l = m.StakedTotalPrincipal.Size()
	n += 1 + l + sovVaults(uint64(l))
	if m.StakedTotalUsers != 0 {
		n += 1 + sovVaults(uint64(m.StakedTotalUsers))
	}
	return n
}

func sovVaults(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVaults(x uint64) (n int) {
	return sovVaults(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Reward) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVaults
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Reward: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Reward: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVaults
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVaults
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVaults
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVaults
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Total.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rewards", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVaults
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVaults
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVaults
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Rewards.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVaults(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVaults
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Position) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVaults
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Position: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Position: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Principal", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVaults
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVaults
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVaults
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Principal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVaults
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVaults
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVaults
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVaults
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVaults
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVaults
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVaults
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.Time, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVaults(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVaults
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PositionEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVaults
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PositionEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PositionEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVaults
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVaults
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVaults
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = append(m.Address[:0], dAtA[iNdEx:postIndex]...)
			if m.Address == nil {
				m.Address = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vault", wireType)
			}
			m.Vault = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVaults
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Vault |= VaultType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Principal", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVaults
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVaults
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVaults
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Principal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVaults
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVaults
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVaults
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVaults
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVaults
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVaults
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVaults
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.Time, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVaults(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVaults
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Stats) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVaults
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Stats: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Stats: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FlexibleTotalPrincipal", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVaults
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVaults
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVaults
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FlexibleTotalPrincipal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FlexibleTotalUsers", wireType)
			}
			m.FlexibleTotalUsers = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVaults
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FlexibleTotalUsers |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FlexibleTotalDistributedRewardsPrincipal", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVaults
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVaults
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVaults
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FlexibleTotalDistributedRewardsPrincipal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakedTotalPrincipal", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVaults
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVaults
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVaults
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StakedTotalPrincipal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakedTotalUsers", wireType)
			}
			m.StakedTotalUsers = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVaults
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StakedTotalUsers |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipVaults(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVaults
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVaults(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVaults
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVaults
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVaults
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVaults
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVaults
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVaults
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVaults        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVaults          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVaults = fmt.Errorf("proto: unexpected end of group")
)
